Version 4
SymbolType BLOCK
RECTANGLE Normal -48 144 95 -80
PIN 0 -80 TOP 8
PINATTR PinName Vdd
PINATTR SpiceOrder 1
PIN 0 144 BOTTOM 8
PINATTR PinName Vss
PINATTR SpiceOrder 2
PIN 96 32 RIGHT 8
PINATTR PinName adj
PINATTR SpiceOrder 3
PIN 96 96 RIGHT 8
PINATTR PinName PWRBAD_
PINATTR SpiceOrder 4
PIN 96 -64 RIGHT 8
PINATTR PinName Vout
PINATTR SpiceOrder 5
PIN 96 64 RIGHT 8
PINATTR PinName Vimon
PINATTR SpiceOrder 6
PIN -48 0 LEFT 8
PINATTR PinName shutdown_
PINATTR SpiceOrder 7
